import { useState, type ReactNode } from 'react'
import { ArrowRight, BarChart3, BrainCircuit, Camera, Check, ChevronRight, Cpu, Database, Globe2, Home, MapPinned, Menu, Navigation, Radar, Route, ScanLine, Sparkles, Target, TrendingUp, Trophy, Waves, X } from 'lucide-react'
import { type Lang, type Bi, copy, customers, comparison, unitRanges, costCards, team, marketMetrics, robotCategories, shipmentTrend, topVendors, regions, vacuumShares, vacuumBrands, outlookMetrics, marketSignals } from './data/content'

const base = import.meta.env.BASE_URL

export default function App() {
  const [lang,setLang]=useState<Lang>('en'); const [menu,setMenu]=useState(false); const t=copy[lang]; const tx=(v:Bi)=>v[lang]
  return <div className="min-h-screen overflow-x-hidden bg-[#f7f9fc] text-[#142039]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur-xl">
      <div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 md:px-10">
        <a href="#top" className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-blue-600 text-white"><ScanLine size={18}/></span>EcloVision</a>
        <nav className="hidden gap-7 text-sm text-slate-600 lg:flex">{['overview','market','product','customers','economics','financing'].map((id,i)=><a key={id} href={`#${id}`} className="hover:text-blue-600">{t.nav[i]}</a>)}</nav>
        <div className="flex items-center gap-2"><div className="flex rounded-full border border-slate-200 bg-slate-50 p-1 text-xs"><button onClick={()=>setLang('zh')} className={`rounded-full px-3 py-1.5 ${lang==='zh'?'bg-white text-blue-700 shadow-sm':'text-slate-500'}`}>中文</button><button onClick={()=>setLang('en')} className={`rounded-full px-3 py-1.5 ${lang==='en'?'bg-white text-blue-700 shadow-sm':'text-slate-500'}`}>EN</button></div><button aria-label="Menu" onClick={()=>setMenu(!menu)} className="p-2 lg:hidden">{menu?<X/>:<Menu/>}</button></div>
      </div>{menu&&<div className="border-t bg-white px-5 py-3 lg:hidden">{['overview','market','product','customers','economics','financing'].map((id,i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)} className="block py-2 text-sm">{t.nav[i]}</a>)}</div>}
    </header>

    <main>
      <section id="top" className="grid-bg relative overflow-hidden bg-white pt-16"><div className="mx-auto grid min-h-[780px] max-w-[1440px] items-center gap-12 px-5 py-24 md:px-10 lg:grid-cols-[1.05fr_.95fr]">
        <div><Eyebrow>{t.eyebrow}</Eyebrow><h1 className="mt-7 max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-[#091a3a] sm:text-6xl lg:text-8xl">EcloVision<br/><span className="text-blue-600">{t.title}</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">{t.intro}</p><div className="mt-10 flex flex-wrap gap-3"><a href="#overview" className="flex items-center gap-2 rounded-full bg-blue-600 px-6 py-3.5 font-medium text-white">{t.view}<ArrowRight size={17}/></a><a href="mailto:contact@eclovision.ai" className="rounded-full border border-slate-300 bg-white px-6 py-3.5 font-medium">{t.contact}</a></div></div>
        <EdgeDiagram lang={lang}/>
      </div></section>

      <PageSection id="overview" eyebrow={t.overview} title={t.overviewTitle} text={t.overviewText}>
        <CapabilityStrip lang={lang}/>
        <div className="mt-16"><Subhead label={t.team} title={t.teamTitle}/><TeamSection lang={lang} tx={tx}/></div>
      </PageSection>

      <PageSection id="market" eyebrow={t.market} title={t.marketTitle} text={t.marketText} tint>
        <MarketOpportunity lang={lang} tx={tx}/>
      </PageSection>

      <PageSection eyebrow={t.stack} title={t.stackTitle}>
        <SlideVisual src="capabilities.png" alt="Core capabilities of robots" caption={t.original}/>
      </PageSection>

      <PageSection eyebrow={t.problem} title={t.problemTitle} tint>
        <div className="grid gap-6 lg:grid-cols-2"><SlideVisual src="pain-points.png" alt="Robot pain point analysis" caption={t.original}/><SlideVisual src="data-collection.png" alt="Resource-intensive data collection" caption={t.original}/></div>
      </PageSection>

      <PageSection id="product" eyebrow={t.product} title={t.productTitle} text={t.overviewText}>
        <div className="grid items-center gap-8 lg:grid-cols-[.72fr_1.28fr]"><ProductLoop lang={lang}/><SlideVisual src="product.png" alt="Visual navigation perception module" caption={t.original}/></div>
      </PageSection>

      <PageSection id="customers" eyebrow={t.customers} title={t.customersTitle} tint>
        <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[1fr_1fr_.9fr] bg-slate-50 px-7 py-4 text-xs font-semibold uppercase tracking-wider text-slate-500 md:grid"><span>{lang==='en'?'Company':'公司'}</span><span>{lang==='en'?'Chinese name':'中文名称'}</span><span>{lang==='en'?'Main business':'主营业务'}</span></div>{customers.map((c,i)=><div key={c.en} className="grid gap-2 border-t border-slate-100 px-7 py-6 md:grid-cols-[1fr_1fr_.9fr]"><span className="font-semibold">{c.en}</span><span className="text-slate-600">{c.zh}</span><span className="text-sm font-medium text-blue-700">{tx(c.domain)}</span></div>)}</div>
      </PageSection>

      <PageSection eyebrow={t.comparison} title={t.comparisonTitle}>
        <ComparisonTable lang={lang} tx={tx}/>
      </PageSection>

      <PageSection id="economics" eyebrow={t.economics} title={t.economicsTitle} tint>
        <div className="grid gap-5 md:grid-cols-3">{unitRanges.map(r=><div key={r.value} className={`rounded-3xl border p-8 ${r.ours?'border-blue-300 bg-blue-600 text-white':'border-slate-200 bg-white'}`}><p className={`text-sm ${r.ours?'text-blue-100':'text-slate-500'}`}>{tx(r.label)}</p><p className="mt-4 text-4xl font-semibold tracking-tight">{r.value}</p></div>)}</div>
        <SlideVisual src="unit-economics.png" alt="Unit economics and cost advantages" caption={t.original}/>
      </PageSection>

      <PageSection eyebrow={t.cost} title={t.costTitle}>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{costCards.map((c,i)=><div key={c.name} className="rounded-3xl border border-slate-200 bg-white p-7"><Cpu className="text-blue-600"/><h3 className="mt-7 text-lg font-semibold">{c.name}</h3><p className="mt-5 text-2xl font-semibold text-blue-700">{c.rmb}</p><p className="mt-1 text-sm text-slate-500">{c.usd}</p></div>)}</div>
      </PageSection>

      <PageSection id="financing" eyebrow={t.financing} title={t.financingTitle} tint>
        <div className="grid gap-6"><SlideVisual src="financing-round-one.png" alt="First-round financing target" caption={t.original}/><div className="grid gap-6 lg:grid-cols-2"><SlideVisual src="financing-path.png" alt="Two-round financing path" caption={t.original}/><SlideVisual src="financing-round-two.png" alt="Second-round financing plan" caption={t.original}/></div></div>
      </PageSection>

      <section className="bg-[#08275f] py-24 text-white"><div className="mx-auto max-w-4xl px-5 text-center"><Globe2 className="mx-auto text-blue-300" size={36}/><h2 className="mt-8 text-4xl font-semibold tracking-[-.04em] md:text-6xl">{t.closing}</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-blue-100">{t.closingText}</p><a href="mailto:contact@eclovision.ai" className="mt-9 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-medium text-blue-800">{t.contact}<ArrowRight size={17}/></a></div></section>
    </main><footer className="bg-[#061a40] px-5 py-8 text-xs text-blue-200/60"><div className="mx-auto flex max-w-[1440px] justify-between"><span>© 2026 EcloVision</span><span>{t.confidential}</span></div></footer>
  </div>
}

function PageSection({id,eyebrow,title,text,children,tint=false}:{id?:string;eyebrow:string;title:string;text?:string;children:ReactNode;tint?:boolean}){return <section id={id} className={`${tint?'bg-[#f0f5fb]':'bg-white'} py-24 md:py-32`}><div className="mx-auto max-w-[1440px] px-5 md:px-10"><div className="max-w-4xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] text-[#091a3a] md:text-6xl">{title}</h2>{text&&<p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{text}</p>}</div><div className="mt-12 md:mt-16">{children}</div></div></section>}
function Eyebrow({children}:{children:ReactNode}){return <span className="inline-flex rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-[11px] font-semibold uppercase tracking-[.16em] text-blue-700">{children}</span>}
function Subhead({label,title}:{label:string;title:string}){return <div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-600">{label}</p><h3 className="mt-3 text-3xl font-semibold tracking-tight">{title}</h3></div>}
function SlideVisual({src,alt,caption}:{src:string;alt:string;caption:string}){return <figure className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_16px_55px_rgba(24,55,95,.09)]"><img src={`${base}slides/${src}`} alt={alt} className="w-full"/><figcaption className="border-t border-slate-100 px-5 py-3 text-xs text-slate-500">{caption}</figcaption></figure>}
function EdgeDiagram({lang}:{lang:Lang}){const a=lang==='en'?['Sensors','Edge AI','Robot action','Field data']:['传感器','边缘 AI','机器人执行','现场数据']; return <div className="relative mx-auto aspect-square w-full max-w-[560px] rounded-full border border-blue-100 bg-blue-50/70 p-[18%]"><div className="grid size-full place-items-center rounded-full bg-blue-600 text-white shadow-[0_25px_80px_rgba(37,99,235,.28)]"><BrainCircuit size={74}/><span className="mt-[-28%] text-xs font-semibold tracking-wider">ECLOVISION</span></div>{[Camera,Cpu,Navigation,Database].map((I,i)=><div key={i} className={`absolute grid size-24 place-items-center rounded-3xl border border-slate-200 bg-white shadow-lg ${['left-0 top-[40%]','left-[40%] top-0','right-0 top-[40%]','bottom-0 left-[40%]'][i]}`}><I className="text-blue-600"/><span className="mt-[-22px] text-[10px] font-medium text-slate-500">{a[i]}</span></div>)}</div>}
function CapabilityStrip({lang}:{lang:Lang}){const a=lang==='en'?['Obstacle detection','3D perception','Localization','Mapping','Planning','Continual learning']:['障碍物检测','3D 感知','定位','建图','规划','持续学习']; const icons=[Radar,Camera,MapPinned,Route,Navigation,Database]; return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{a.map((x,i)=>{const I=icons[i];return <div key={x} className="rounded-2xl border border-slate-200 bg-white p-5"><I className="text-blue-600"/><p className="mt-6 text-sm font-semibold">{x}</p></div>})}</div>}
function TeamSection({lang,tx}:{lang:Lang;tx:(v:Bi)=>string}){return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{team.map((m,i)=><article key={m.name} className="flex flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_14px_45px_rgba(24,55,95,.07)]"><div className="flex items-start justify-between"><img src={`${base}team/${m.image}`} alt={m.name} className="size-28 rounded-full border border-slate-200 object-cover shadow-sm"/><span className="text-xs font-semibold text-slate-300">0{i+1}</span></div><h3 className="mt-6 text-xl font-semibold tracking-tight">{m.name}</h3><p className="mt-1 text-sm font-semibold text-blue-600">{tx(m.role)}</p><div className="my-5 h-px bg-slate-100"/><ul className="space-y-4">{m.points.map((p,j)=><li key={j} className="flex gap-3 text-sm leading-6 text-slate-600"><Check className="mt-1 size-4 shrink-0 text-blue-600"/><span>{tx(p)}</span></li>)}</ul></article>)}</div>}
function MarketOpportunity({lang,tx}:{lang:Lang;tx:(v:Bi)=>string}){
  const colors=['#1473e6','#f4b000','#f47a20','#ff9f1c','#ef3340','#10235c'];
  const labels=lang==='en'?{
    metrics:'Market at a glance',categories:'Main cleaning robot categories',trend:'Shipment growth trend',shipments:'Total shipments (M units)',vendors:'Top 5 global vendors in 2025',vendorNote:'Chinese brands continue to dominate through AI-driven innovation, cordless upgrades and international expansion.',regions:'Regional distribution',outlook:'Smart Vacuum & Lawn Mower Robotics Market Outlook (2025)',vacuum:'Smart vacuum: scale meets strategic realignment',share:'Worldwide smart vacuum company market share, 2023–2025',lawn:'Lawn mower robotics: cordless disruption reshapes the market',wire:'Wire-free',boundary:'Boundary-wire',signals:'Key industry signals',focus:'Investment focus',focusText:'Back companies building multi-category ecosystems, strong AI stacks, and scalable overseas channels.',source:'Sources: IDC Worldwide Cleaning Robot Trackers (2026), IFR World Robotics, Grand View Research, company disclosures, and uploaded research summary.'
  }:{
    metrics:'核心市场指标',categories:'主要清洁机器人品类',trend:'出货量增长趋势',shipments:'总出货量（百万台）',vendors:'2025 年全球前五大厂商',vendorNote:'中国品牌通过 AI 创新、无线产品升级与国际化持续主导全球竞争格局。',regions:'区域分布',outlook:'智能扫地与割草机器人市场展望（2025）',vacuum:'智能扫地机器人：规模增长与战略重构',share:'2023–2025 年全球智能扫地机器人公司市场份额',lawn:'割草机器人：无线化变革重塑市场',wire:'无线',boundary:'边界线',signals:'关键行业信号',focus:'投资重点',focusText:'关注具备多品类生态、强大 AI 技术栈与可规模化海外渠道的企业。',source:'来源：IDC Worldwide Cleaning Robot Trackers（2026）、IFR World Robotics、Grand View Research、公司披露及上传的研究摘要。'
  };
  const catIcons=[Home,Route,ScanLine,Waves];
  return <div className="space-y-16">
    <section><MarketLabel icon={<TrendingUp/>}>{labels.metrics}</MarketLabel><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{marketMetrics.map((m,i)=><article key={m.value} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><TrendingUp size={19}/></span><span className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{m.source}</span></div><div className="mt-7 flex items-end gap-2"><strong className="text-4xl font-semibold tracking-tight text-blue-700">{m.value}</strong><span className="pb-1 text-xs font-semibold text-slate-500">{typeof m.unit==='string'?m.unit:tx(m.unit)}</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{tx(m.label)}</p><p className="mt-2 text-xs font-semibold text-teal-700">{tx(m.note)}</p></article>)}</div></section>
    <section><MarketLabel icon={<Target/>}>{labels.categories}</MarketLabel><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{robotCategories.map((c,i)=>{const I=catIcons[i];return <article key={tx(c.name)} className="rounded-3xl border border-slate-200 bg-white p-6"><I className="text-blue-600"/><h3 className="mt-6 text-lg font-semibold">{tx(c.name)}</h3><div className="mt-5 flex items-baseline gap-2"><strong className="text-3xl text-blue-700">{typeof c.value==='string'?c.value:tx(c.value)}</strong><span className="text-xs font-semibold text-teal-700">{typeof c.note==='string'?c.note:tx(c.note)}</span></div><p className="mt-4 text-sm leading-6 text-slate-500">{tx(c.text)}</p></article>})}</div></section>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-3xl border border-slate-200 bg-white p-6 md:p-8"><MarketLabel icon={<BarChart3/>}>{labels.trend}</MarketLabel><p className="mt-2 text-xs text-slate-400">{labels.shipments}</p><div className="mt-10 grid h-64 grid-cols-3 items-end gap-3 border-b border-slate-200 px-1 sm:gap-5 sm:px-2">{shipmentTrend.map((d,i)=><div key={d.period} className="flex h-full min-w-0 flex-col justify-end"><div className="mb-3 flex flex-col items-center gap-0.5 text-[10px] font-semibold sm:flex-row sm:justify-between sm:text-[11px]"><span className="text-teal-700">+{d.lawn}%</span><span className="text-blue-500">+{d.window}%</span></div><div className="relative mx-auto w-2/3 rounded-t-xl bg-gradient-to-t from-blue-700 to-blue-400" style={{height:`${d.shipments/13*72}%`}}><span className="absolute left-1/2 top-2 -translate-x-1/2 text-xs font-semibold text-white sm:text-sm">{d.shipments}M</span></div><p className="py-3 text-center text-xs font-medium">{d.period}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-5 text-xs text-slate-500"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-blue-600"/>Total shipments</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-teal-600"/>Lawn mower YoY</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-blue-400"/>Window robot YoY</span></div></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-6 md:p-8"><MarketLabel icon={<Trophy/>}>{labels.vendors}</MarketLabel><div className="mt-6 overflow-hidden rounded-2xl border border-slate-100">{topVendors.map(v=><div key={v.rank} className="grid grid-cols-[34px_1fr_70px_55px] items-center gap-2 border-t border-slate-100 px-4 py-3 text-sm first:border-0"><span className="grid size-6 place-items-center rounded-full bg-blue-600 text-xs font-semibold text-white">{v.rank}</span><strong>{v.name}</strong><span className="text-slate-500">{v.shipments}</span><span className="font-semibold text-blue-700">{v.share}</span></div>)}</div><p className="mt-6 rounded-2xl bg-blue-50 p-4 text-sm leading-6 text-blue-900">{labels.vendorNote}</p></section>
    </div>
    <section><MarketLabel icon={<Globe2/>}>{labels.regions}</MarketLabel><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{regions.map(r=><article key={tx(r.name)} className="rounded-3xl border border-slate-200 bg-white p-6"><Globe2 className="text-teal-600"/><h3 className="mt-5 font-semibold">{tx(r.name)}</h3><strong className="mt-3 block text-2xl text-teal-700">{typeof r.stat==='string'?r.stat:tx(r.stat)}</strong><p className="mt-3 text-sm leading-6 text-slate-500">{tx(r.text)}</p></article>)}</div></section>
    <section><MarketLabel icon={<TrendingUp/>}>{labels.outlook}</MarketLabel><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{outlookMetrics.map((m,i)=><article key={m.value} className={`rounded-3xl border bg-white p-6 ${i===1||i===2?'border-teal-200':'border-blue-200'}`}><strong className={`text-3xl tracking-tight ${i===1||i===2?'text-teal-700':'text-blue-700'}`}>{m.value}</strong><h3 className="mt-5 font-semibold leading-6">{tx(m.label)}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{tx(m.note)}</p><p className="mt-5 text-[10px] font-semibold uppercase tracking-wider text-slate-400">Source: IDC 2026</p></article>)}</div></section>
    <section><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-6 md:p-8"><MarketLabel icon={<BarChart3/>}>{labels.vacuum}</MarketLabel><h3 className="mt-5 text-lg font-semibold">{labels.share}</h3><div className="mt-8 flex h-72 items-end justify-around gap-5">{vacuumShares.map(y=><div key={y.year} className="flex h-full w-24 flex-col justify-end"><div className="flex h-[88%] flex-col-reverse overflow-hidden rounded-t-lg">{y.values.map((v,i)=><div key={i} className="grid min-h-[18px] place-items-center text-[10px] font-semibold text-white" style={{height:`${v}%`,background:colors[i]}}>{v>=7?v+'%':''}</div>)}</div><p className="pt-3 text-center text-sm font-semibold">{y.year}</p></div>)}</div><div className="mt-6 flex flex-wrap gap-x-4 gap-y-2">{vacuumBrands.map((b,i)=><span key={b} className="flex items-center gap-2 text-xs text-slate-500"><i className="size-2 rounded-sm" style={{background:colors[i]}}/>{b}</span>)}</div></div>
      <div className="rounded-3xl border border-teal-200 bg-white p-6 md:p-8"><MarketLabel icon={<Route/>}>{labels.lawn}</MarketLabel><div className="mt-8 grid items-center gap-8 sm:grid-cols-[180px_1fr]"><div className="mx-auto grid size-44 place-items-center rounded-full" style={{background:'conic-gradient(#0f9f9a 0 66.2%, #d8dee8 66.2% 100%)'}}><div className="grid size-28 place-items-center rounded-full bg-white text-center"><strong className="text-2xl text-teal-700">1.99M</strong><span className="mt-[-22px] text-xs text-slate-500">+63.8% YoY</span></div></div><div className="space-y-4"><div className="rounded-2xl bg-teal-50 p-4"><strong className="text-2xl text-teal-700">66.2%</strong><p className="text-sm">{labels.wire} · +182.4% YoY</p></div><div className="rounded-2xl bg-slate-100 p-4"><strong className="text-2xl text-slate-700">33.8%</strong><p className="text-sm">{labels.boundary} · −10.1% YoY</p></div></div></div><ul className="mt-8 space-y-3 text-sm leading-6 text-slate-600">{(lang==='en'?['Adoption is accelerating as RTK, vision, and LiDAR navigation mature.','Simple installation and out-of-box usability are driving consumer uptake.','Chinese manufacturers lead the wire-free transition and product iteration cycle.','The category is still in early transformation, leaving room for new winners.']:['随着 RTK、视觉与 LiDAR 导航成熟，市场应用正在加速。','简单安装与开箱即用推动消费者采用。','中国厂商引领无线化转型与产品迭代周期。','该品类仍处于早期变革阶段，新进入者仍有机会。']).map(x=><li key={x} className="flex gap-3"><Check className="mt-1 size-4 shrink-0 text-teal-600"/>{x}</li>)}</ul></div>
    </div></section>
    <section className="rounded-3xl border border-blue-200 bg-blue-50 p-6 md:p-8"><MarketLabel icon={<Sparkles/>}>{labels.signals}</MarketLabel><div className="mt-6 grid gap-4 md:grid-cols-3">{marketSignals.map((s,i)=><div key={i} className="rounded-2xl bg-white p-5 text-sm leading-6 text-slate-600"><span className="mb-5 grid size-9 place-items-center rounded-xl bg-blue-100 font-semibold text-blue-700">0{i+1}</span>{tx(s)}</div>)}</div><div className="mt-5 flex gap-3 rounded-2xl bg-blue-700 p-5 text-sm text-white"><Target className="shrink-0"/><p><strong>{labels.focus}:</strong> {labels.focusText}</p></div></section>
    <p className="text-xs leading-5 text-slate-400">{labels.source}</p>
  </div>
}
function MarketLabel({icon,children}:{icon:ReactNode;children:ReactNode}){return <div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-blue-100 text-blue-700">{icon}</span><h3 className="text-lg font-semibold tracking-tight">{children}</h3></div>}
function ProductLoop({lang}:{lang:Lang}){const a=lang==='en'?['Camera / Sensors','Edge AI Module','Perception / Localization / Planning','Robot Actions','Data Feedback','Continual Improvement']:['相机 / 传感器','边缘 AI 模块','感知 / 定位 / 规划','机器人执行','数据反馈','持续优化']; return <div className="space-y-3">{a.map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-blue-50 text-xs font-semibold text-blue-700">{i+1}</span><span className="text-sm font-medium">{x}</span>{i<5&&<ChevronRight className="ml-auto text-slate-300" size={16}/>}</div>)}</div>}
function ComparisonTable({lang,tx}:{lang:Lang;tx:(v:Bi)=>string}){const heads=lang==='en'?['Company','Product','CPU','GPU / NPU','Function & Selling Point','Price']:['公司','产品','CPU','GPU / NPU','功能与卖点','价格'];return <div className="overflow-x-auto rounded-3xl border border-slate-200"><table className="w-full min-w-[1050px] bg-white text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr>{heads.map(h=><th className="px-5 py-4" key={h}>{h}</th>)}</tr></thead><tbody>{comparison.map((r,i)=><tr key={i} className={`border-t border-slate-100 ${r.ours?'bg-blue-50/80':''}`}><td className={`px-5 py-5 font-semibold ${r.ours?'text-blue-700':''}`}>{r.company}</td><td className="px-5 py-5">{r.product}</td><td className="px-5 py-5 text-xs">{r.cpu}</td><td className="px-5 py-5 text-xs">{r.gpu}</td><td className="px-5 py-5 text-xs leading-5">{tx(r.fn)}</td><td className={`px-5 py-5 font-semibold ${r.ours?'text-blue-700':''}`}>{r.price}</td></tr>)}</tbody></table></div>}
